
server:
  port: 8503
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instance-id: microservice-provider-user
  application:
    name: microservice-provider-user
 