eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8020

spring:
  application:
    name: microservice-consumer-movie-ribbon-customizing-properties

## 配置文件指定ribbon负载均衡策略
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule